stages:
  get_data:
    cmd: python ./pipeline/get_data.py
    deps: 
    - ./pipeline/get_data.py
    outs:
    - ./data/raw_data.npy
  process_data:
    cmd: python ./pipeline/process_data.py
    deps:
    - ./pipeline/process_data.py
    - ./data/raw_data.npy
    params:
    - process_data.test_size
    metrics:
    - ./metrics/process_data_metrics.yaml